CREATE TABLE VEM_SER.ESTUDANTE (
 id_estudante NUMBER,
 nome VARCHAR2(200) NOT NULL,
 data_nascimento DATE NOT NULL,
 nm_matricula NUMBER (10) NOT NULL, 
 ativo CHAR,
 PRIMARY KEY(id_pessoa)
);

CREATE SEQUENCE VEM_SER.seq_estudante
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

INSERT INTO VEM_SER.ESTUDANTE (ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NM_MATRICULA, ATIVO) 
VALUES (SEQ_ESTUDANTE.nextval, 'Marcio', TO_DATE('08-09-1992', 'dd-mm-yyyy'), 1234567891, 'S');

INSERT INTO VEM_SER.ESTUDANTE (ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NM_MATRICULA, ATIVO)
VALUES (SEQ_ESTUDANTE.nextval, 'Julio', TO_DATE('08-09-1993', 'dd-mm-yyyy'), 1234567892, 'N');

INSERT INTO VEM_SER.ESTUDANTE (ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NM_MATRICULA, ATIVO)
VALUES (SEQ_ESTUDANTE.nextval, 'Romeu', TO_DATE('09-09-1992', 'dd-mm-yyyy'), 1234567893, 'S');

INSERT INTO VEM_SER.ESTUDANTE (ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NM_MATRICULA, ATIVO)
VALUES (SEQ_ESTUDANTE.nextval, 'Carlos', TO_DATE('10-09-1992', 'dd-mm-yyyy'), 1234567894, 'S');

INSERT INTO VEM_SER.ESTUDANTE (ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NM_MATRICULA, ATIVO)
VALUES (SEQ_ESTUDANTE.nextval, 'Maria', TO_DATE('11-09-1992', 'dd-mm-yyyy'), 1234567895, 'N');

INSERT INTO VEM_SER.ESTUDANTE (ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NM_MATRICULA, ATIVO)
VALUES (SEQ_ESTUDANTE.nextval, 'Ana', TO_DATE('08-09-1995', 'dd-mm-yyyy'), 1234567896, 'N');

INSERT INTO VEM_SER.ESTUDANTE (ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NM_MATRICULA, ATIVO)
VALUES (SEQ_ESTUDANTE.nextval, 'Joao', TO_DATE('08-09-1991', 'dd-mm-yyyy'), 1234567897, 'S');

INSERT INTO VEM_SER.ESTUDANTE (ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NM_MATRICULA, ATIVO)
VALUES (SEQ_ESTUDANTE.nextval, 'Carolina', TO_DATE('08-09-1990', 'dd-mm-yyyy'), 1234567898, 'S');

INSERT INTO VEM_SER.ESTUDANTE (ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NM_MATRICULA, ATIVO)
VALUES (SEQ_ESTUDANTE.nextval, 'Julia', TO_DATE('08-09-1989', 'dd-mm-yyyy'), 1234567899, 'S');

INSERT INTO VEM_SER.ESTUDANTE (ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NM_MATRICULA, ATIVO)
VALUES (SEQ_ESTUDANTE.nextval, 'Mauricio', TO_DATE('08-10-1992', 'dd-mm-yyyy'), 1234567890, 'N');

SELECT * FROM VEM_SER.ESTUDANTE;