
SELECT * FROM PAIS 
ORDER BY NOME DESC;

SELECT LOGRADOURO, CEP FROM ENDERECO
WHERE UPPER(LOGRADOURO) LIKE 'A%';

SELECT * FROM ENDERECO
WHERE CEP LIKE '%0';

SELECT * FROM ENDERECO
WHERE NUMERO BETWEEN 1 AND 100;

SELECT * FROM ENDERECO
WHERE UPPER(LOGRADOURO) LIKE 'RUA%'
ORDER BY CEP DESC;

SELECT COUNT(ID_ENDERECO) FROM ENDERECO;

SELECT ID_CIDADE, COUNT(ID_ENDERECO) AS ENDERECOS_NA_CIDADE FROM ENDERECO
GROUP BY ID_CIDADE
ORDER BY ID_CIDADE;


